New Event & 3rd Party List Section
mage-os/mageos-common-async-events pull request #11
Opened 2024-06-13 15:13 UTC by adamzero1

- added `customer.login` event
- added a "3rd Party" section to the README to hopefully make it easier for people to share other common events, that may not belong in this repo.

2024-06-14 00:56 UTC, gowrizrh approved these changes

2024-06-14 00:56 UTC, gowrizrh commented
LGTM :heavy_check_mark:

2024-06-14 06:58 UTC, avstudnitz commented on Observer/CustomerLoginObserver.php
> +     * @see @event customer_save_after
Please change the comment to `customer_login`.

2024-06-14 07:00 UTC, avstudnitz requested changes
Great addition, thanks! Just one change in the comment needed.
Also, the third party module list is great. Perhaps it would be even better to add a link to these modules on GitHub?

2024-09-16 06:58 UTC, avstudnitz commented
Transferred the commit to #13

2024-09-16 06:58 UTC, closed without merging